import type { Article, Category, NavItem } from './types';

export const CATEGORIES: Category[] = [
  'Credit Cards',
  'Insurance',
  'Loans & Mortgages',
  'Investing & Retirement',
  'Budgeting & Apps'
];

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', path: '/' },
  { label: 'Credit Cards', path: '/category/credit-cards' },
  { label: 'Insurance', path: '/category/insurance' },
  { label: 'Loans', path: '/category/loans-mortgages' },
  { label: 'Investing', path: '/category/investing-retirement' },
  { label: 'Mortgage Calculator', path: '/tool/mortgage-calculator' },
];

// Initial starter articles as requested
export const INITIAL_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'Best Credit Cards for Cashback in 2025',
    slug: 'best-credit-cards-cashback-2025',
    category: 'Credit Cards',
    summary: 'Maximize your spending with our top picks for cashback credit cards this year. From groceries to gas, find out which cards offer the highest returns.',
    publishDate: '2025-01-15',
    author: 'Sarah Jenkins',
    imageUrl: 'https://picsum.photos/seed/finance1/800/600',
  },
  {
    id: '2',
    title: 'Top 5 Affordable Health Insurance Plans for Families',
    slug: 'affordable-health-insurance-families',
    category: 'Insurance',
    summary: 'Protecting your family shouldn\'t break the bank. We analyze the top 5 cost-effective health insurance plans offering comprehensive coverage.',
    publishDate: '2025-01-20',
    author: 'Dr. Mark Stevens',
    imageUrl: 'https://picsum.photos/seed/finance2/800/600',
  },
  {
    id: '3',
    title: 'How to Get Approved for a Personal Loan with Bad Credit',
    slug: 'personal-loan-bad-credit-guide',
    category: 'Loans & Mortgages',
    summary: 'Bad credit doesn\'t mean zero options. Learn the strategic steps to improve your approval odds and secure a personal loan when you need it most.',
    publishDate: '2025-02-01',
    author: 'Michael Ross',
    imageUrl: 'https://picsum.photos/seed/finance3/800/600',
  },
  {
    id: '4',
    title: 'Car Insurance Discounts You Didn’t Know About',
    slug: 'hidden-car-insurance-discounts',
    category: 'Insurance',
    summary: 'Stop overpaying for auto insurance. Uncover hidden discounts for safe driving, bundling, low mileage, and more that agents often forget to mention.',
    publishDate: '2025-02-03',
    author: 'Sarah Jenkins',
    imageUrl: 'https://picsum.photos/seed/finance4/800/600',
  },
  {
    id: '5',
    title: 'Beginner’s Guide to Investing in Index Funds',
    slug: 'beginners-guide-index-funds',
    category: 'Investing & Retirement',
    summary: 'Warren Buffett recommends them. Learn why index funds are the safest bet for long-term wealth building and how to start with just $50.',
    publishDate: '2025-02-05',
    author: 'David Chen',
    imageUrl: 'https://picsum.photos/seed/finance5/800/600',
  },
  {
    id: '6',
    title: 'Travel Insurance: Do You Really Need It?',
    slug: 'travel-insurance-necessity',
    category: 'Insurance',
    summary: 'Planning a trip? Before you click "decline" on that insurance offer, understand when it is absolutely critical and when it is a waste of money.',
    publishDate: '2025-02-08',
    author: 'Jessica Bloom',
    imageUrl: 'https://picsum.photos/seed/finance6/800/600',
  },
  {
    id: '7',
    title: 'Mortgage Calculator: How Much House Can You Afford?',
    slug: 'mortgage-affordability-guide',
    category: 'Loans & Mortgages',
    summary: 'Don\'t become house poor. Use our guide and built-in calculator logic to determine your true budget based on interest rates and down payments.',
    publishDate: '2025-02-10',
    author: 'Michael Ross',
    imageUrl: 'https://picsum.photos/seed/finance7/800/600',
  },
  {
    id: '8',
    title: 'Top 10 Budgeting Apps for 2025',
    slug: 'top-budgeting-apps-2025',
    category: 'Budgeting & Apps',
    summary: 'From YNAB to Mint alternatives, we review the best apps to track your net worth, manage subscriptions, and curb impulse spending.',
    publishDate: '2025-02-12',
    author: 'Alex Johnson',
    imageUrl: 'https://picsum.photos/seed/finance8/800/600',
  },
  {
    id: '9',
    title: 'Life Insurance for Young Adults: Why Start Early?',
    slug: 'life-insurance-young-adults',
    category: 'Insurance',
    summary: 'Lock in low rates while you are young and healthy. We explain term vs. whole life and why waiting could cost you thousands.',
    publishDate: '2025-02-14',
    author: 'Dr. Mark Stevens',
    imageUrl: 'https://picsum.photos/seed/finance9/800/600',
  },
  {
    id: '10',
    title: 'Crypto vs. Stocks: Which Investment Is Safer in 2025',
    slug: 'crypto-vs-stocks-safety-2025',
    category: 'Investing & Retirement',
    summary: 'The debate continues. We analyze market volatility, regulation changes, and historical returns to help you decide where to park your savings.',
    publishDate: '2025-02-15',
    author: 'David Chen',
    imageUrl: 'https://picsum.photos/seed/finance10/800/600',
  },
];